spring:
  application:
    name: cultureapp

  datasource:
    url: jdbc:mysql://localhost:3306/tourism_db
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

kakao:
  api:
    key: ${KAKAO_API_KEY}
    geocode-url: https://dapi.kakao.com/v2/local/geo/coord2regioncode.json
    address-url: https://dapi.kakao.com/v2/local/search/address.json

ai:
  service:
    base-url: ${AI_SERVICE_BASE_URL:http://localhost:8000}